# Generated by Django 3.2.8 on 2021-10-18 20:57

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='board',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
